events {
    worker_connections 1024;
}

http {

    
    server {
        listen 80;

        root /usr/share/nginx/html;

        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /api/users {
            proxy_pass http://user_services:8000/users;
        }

        location /api/products {
            proxy_pass http://product_services:8000/products;
        }

        
    }
}