events {
    worker_connections 1024;
}

http {

    upstream user_cluster {
        server user_services:8000;
    }

    server {
        listen 80;

        location /users {
            proxy_pass http://user_cluster;
        }

        location /products {
            proxy_pass http://product_services:8000;
        }

        location / {
            proxy_pass http://general_services:8000;
        }
    }
}